import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "../components/ui/sonner";
import Providers from "./provider"; // Import Providers

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {" "}
          {/* Wrap everything with Providers */}
          <div className="mx-6 md:mx-16">
            <Header />
            <Toaster />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
